# 5.4. Custom Layers

## 5.4.1. Layers without Parameters

In [1]:
import torch
from torch import nn
from torch.nn import functional as F


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [4]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(4.6566e-10, grad_fn=<MeanBackward0>)

## 5.4.2. Layers with Parameters

In [5]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [6]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-1.8615,  0.6009, -0.5605],
        [ 0.7912, -1.3849, -0.7232],
        [-0.1723,  1.6477, -0.0481],
        [-0.1405,  0.1074, -0.7180],
        [ 0.8414, -2.1044, -0.2258]], requires_grad=True)

In [7]:
linear(torch.rand(2, 5))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.],
        [0.]])

## 5.4.3. Summary

We can design custom layers via the basic layer class. This allows us to define flexible new layers that behave differently from any existing layers in the library.

Once defined, custom layers can be invoked in arbitrary contexts and architectures.

Layers can have local parameters, which can be created through built-in functions.