# 2.1. Data Manipulation
## 2.1.1. Getting Started

In [1]:
import torch

# create a vector of evenly spaced values, starting at 0 (included) and ending at n (not included).
x = torch.arange(12, dtype=torch.float32)
x 

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [2]:
# the length along each axis
x.shape 

torch.Size([12])

In [3]:
# the total number of elements in a tensor
x.numel()

12

In [4]:
# transform our tensor, x, from a row vector with shape (12,) to a matrix with shape (3, 4)
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [5]:
# create a tensor representing a tensor with all elements set to 0 and a shape of (2, 3, 4)
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [6]:
# create tensors with each element set to 1
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [7]:
# creates a tensor with shape (3, 4). 
# Each of its elements is randomly sampled from a standard Gaussian (normal) distribution with a mean of 0 and a standard deviation of 1

torch.randn(3, 4)

tensor([[ 1.4856, -0.4029,  2.2246,  1.8995],
        [-0.2639, -1.3286, -0.0803, -0.1276],
        [-0.2604, -0.1201, -0.0617,  1.2129]])

In [8]:
# specify the exact values for each element in the desired tensor
# the outermost list corresponds to axis 0, and the inner list to axis 1
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 2.1.2. Operations

In [9]:
## (+, -, *, /, and **)
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # The ** operator is exponentiation

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [10]:
# exponentiation
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [11]:
# concatenate multiple tensors together
# rows (axis 0, the first element of the shape) vs. columns (axis 1, the second element of the shape)
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [12]:
# binary tensor via logical statements.
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [13]:
# summing all the elements
X.sum()

tensor(66.)

## 2.1.3. Broadcasting Mechanism

In [14]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [15]:
# Since a and b are  3×1  and  1×2  matrices respectively, their shapes do not match up if we want to add them. 
# We broadcast the entries of both matrices into a larger  3×2  matrix as follows: 
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 2.1.4. Indexing and Slicing

In [16]:
# [-1] selects the last element and [1:3] selects the second and the third elements
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [17]:
# write elements of a matrix by specifying indices
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [18]:
# [0:2, :] accesses the first and second rows, where : takes all the elements along axis 1 (column).
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 2.1.5. Saving Memory

In [19]:
# Python first evaluates Y + X, allocating new memory for the result and then makes Y point to this new location in memory.
before = id(Y)
Y = Y + X
id(Y) == before

False

In [20]:
# create a new matrix Z with the same shape as another Y
# using zeros_like to allocate a block of  0  entries
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 3130028085632
id(Z): 3130028085632


In [21]:
# 
before = id(X)
X += Y
id(X) == before

True

## 2.1.6. Conversion to Other Python Objects

In [22]:
# Converting to a NumPy tensor (ndarray), or vice versa
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [23]:
# convert a size-1 tensor to a Python scalar
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 2.1.7. Summary

The main interface to store and manipulate data for deep learning is the tensor ( n -dimensional array). It provides a variety of functionalities including basic mathematics operations, broadcasting, indexing, slicing, memory saving, and conversion to other Python objects.