# 2.6. Probability
## 2.6.1. Basic Probability Theory

In [1]:
%matplotlib inline
import torch
from torch.distributions import multinomial
from d2l import torch as d2l

fair_probs = torch.ones([6]) / 6
multinomial.Multinomial(1, fair_probs).sample()

tensor([0., 0., 0., 0., 0., 1.])

In [2]:
multinomial.Multinomial(10, fair_probs).sample()

tensor([2., 0., 1., 4., 2., 1.])

In [3]:
# Store the results as 32-bit floats for division
counts = multinomial.Multinomial(1000, fair_probs).sample()
counts / 1000  # Relative frequency as the estimate

tensor([0.1700, 0.1580, 0.1580, 0.1550, 0.1780, 0.1810])

In [4]:
counts = multinomial.Multinomial(10, fair_probs).sample((500,))
cum_counts = counts.cumsum(dim=0)
estimates = cum_counts / cum_counts.sum(dim=1, keepdims=True)

d2l.set_figsize((6, 4.5))
for i in range(6):
    d2l.plt.plot(estimates[:, i].numpy(),
                 label=("P(die=" + str(i + 1) + ")"))
d2l.plt.axhline(y=0.167, color='black', linestyle='dashed')
d2l.plt.gca().set_xlabel('Groups of experiments')
d2l.plt.gca().set_ylabel('Estimated probability')
d2l.plt.legend();

### 2.6.1.1. Axioms of Probability Theory
### 2.6.1.2. Random Variables

## 2.6.2. Dealing with Multiple Random Variables
### 2.6.2.1. Joint Probability
### 2.6.2.2. Conditional Probability
### 2.6.2.3. Bayes' theorem
### 2.6.2.4. Marginalization
### 2.6.2.5. Independence
### 2.6.2.6. Application

## 2.6.3. Expectation and Variance

Check the contents in website.

## 2.6.4. Summary

We can sample from probability distributions.

We can analyze multiple random variables using joint distribution, conditional distribution, Bayes’ theorem, marginalization, and independence assumptions.

Expectation and variance offer useful measures to summarize key characteristics of probability distributions.